version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  payara:
    build: .
    container_name: payara
    ports:
      - "8080:8080"
      - "4848:4848"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DB=books_db
      - MYSQL_USER=yourUsername
      - MYSQL_PASSWORD=yourPassword
    networks:
      - my_network
    depends_on:
      - mysql
    volumes:
      - ./jakartaee-rest/payara/passwordFile:/opt/payara/passwordFile

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: books_db
      MYSQL_USER: yourUsername
      MYSQL_PASSWORD: yourPassword
    networks:
      - my_network      
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./jakartaee-rest/mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
