version: '3.8'
services:
  payara:
    build: .
    container_name: payara
    ports:
      - "8080:8080"
      - "4848:4848"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DB=books_db
      - MYSQL_USER=yourUsername
      - MYSQL_PASSWORD=yourPassword
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: books_db
      MYSQL_USER: yourUsername
      MYSQL_PASSWORD: yourPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./jakartaee-rest/mysql-init:/docker-entrypoint-initdb.d
      - ./jakartaee-rest/mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
